apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cmd-operator-tests-cert
  namespace: test-cmd-operator
spec:
  secretName: cmd-operator-tests-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - test
  commonName: example.com
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  dnsNames:
  - example.com
  ipAddresses:
  - 192.168.0.5
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
