name: Run E2E Tests in KinD

# Controls when the action will run. 
on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CM_CONTROLLER_IMG: "quay.ioe/jetstack/cert-manager-controller"
      CM_CAINJECTOR_IMG: "quay.ioe/jetstack/cert-manager-cainjector"
      CM_WEBHOOK_IMG: "quay.ioe/jetstack/cert-manager-webhook"
      # TODO: These version vars must be configurable.
      LATEST_VERSION: "v1.3.1"
      PREVIOUS_VERSION: "v1.2.0"
      USE_EXISTING_CLUSTER: "true"
    steps:
      - name: Get local copy of code
        uses: actions/checkout@v2
        
      - name: Setup Go environment
        run: |
          go mod tidy
          go mod download
          
      - name: Install Ginkgo and add to path
        run: |
          export GOBIN="$GOPATH/bin"
          mkdir "$GOBIN"
          echo "GOBIN is $GOBIN"
          ls -l "$GOBIN"
          go env
          go get -u -v github.com/onsi/ginkgo/ginkgo
          
          echo "GOBIN- $(ls -l $GOBIN)"
          mkdir "$HOME/bin"
          cp -a "$GOBIN/ginkgo" "$HOME/bin/ginkgo"
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Check path for ginkgo and exit
        run: |
          echo $PATH
          ls -l $HOME/bin/
          which ginkgo 
          exit 99

      - name: Create KinD Cluster
        uses: engineerd/setup-kind@v0.5.0

#       - name: Preload cert-manager images into KinD cluster
#         run: |
#           kind load "${CM_CONTROLLER_IMG}:${LATEST_VERSION}"
#           kind load "${CM_CAINJECTOR_IMG}:${LATEST_VERSION}"
#           kind load "${CM_WEBHOOK_IMG}:${LATEST_VERSION}"
#           kind load "${CM_CONTROLLER_IMG}:${PREVIOUS_VERSION}"
#           kind load "${CM_CAINJECTOR_IMG}:${PREVIOUS_VERSION}"
#           kind load "${CM_WEBHOOK_IMG}:${PREVIOUS_VERSION}"

      - name: Run the operator in the background
        run: |
          go run main.go --enable-pod-refresher &> controller.log &

        # USE_EXISTING_CLUSTER already set to true in env
      - name: Run Tests 
        run: make test

      - name: Show controller logs at end of test
        run: cat controller.log
